# -*- coding: utf-8 -*-
"""units and measurement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpjfssOTdbLbUNSWC-4D4jBxjm1HiBU8
"""

length_units = {

    "mm": 0.001,
    "cm": 0.01,
    "m": 1.0,
    "km": 1000.0,
    "in": 0.0254,      # Inch
    "ft": 0.3048,      # Foot
    "yd": 0.9144,      # Yard
    "mi": 1609.344,    # Mile

    # Astronomical
    "au": 149597870700.0, # Astronomical Unit (Earth to Sun)
    "ly": 9.461e15
}
from_unit = input("Unit from which you wanna covert.")
value_from = float(input("Value for the unit you gave for 1st."))
to_unit = input("Unit to which you wanna convert.")


metres = length_units[from_unit] * value_from


result = metres / length_units[to_unit]

print(f"{value_from} {from_unit} converted to {to_unit} is {result}")

